if (!requireNamespace("BiocManager", quietly = TRUE)){
	install.packages("BiocManager")
	BiocManager::install()	
}

library("BiocManager")

install("BiocParallel", update=FALSE)
install("foreach", update=FALSE)
install("data.table", update=FALSE)
install("gage", update=FALSE)
install("AnnotationDbi", update=FALSE)
install("stats4", update=FALSE)
install("BiocGenerics", update=FALSE)
install("parallel", update=FALSE)
install("DESeq2", update=FALSE)
install("sva", update=FALSE)
install("ggplot2", update=FALSE)
install("AnnotationDbi", update=FALSE)
install("fgsea", update=FALSE)
install("ggrepel", update=FALSE)
install("rjson", update=FALSE)
install("circlize", update=FALSE)
install("ComplexHeatmap", update=FALSE)
install("ggbeeswarm", update=FALSE)
install("uwot", update=FALSE)
install("dbscan", update=FALSE)
install("MASS", update=FALSE)
install("simplifyEnrichment", update=FALSE)
install("WGCNA", update=FALSE)
install("qualpalr", update=FALSE)
install("reshape2", update=FALSE)
install("RJSONIO", update=FALSE)
install("stringr", update=FALSE)
install("doParallel", update=FALSE)
install("scales", update=FALSE)
install("pathview", update=FALSE)