if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install()

library("BiocManager")
install("AnnotationDbi",update=FALSE)
install("AnnotationDbi",update=FALSE)
install("ComplexHeatmap",update=FALSE)
install("DESeq2",update=FALSE)
install("GO.db",update=FALSE)
install("RColorBrewer",update=FALSE)
install("Rcpp",update=FALSE)
install("circlize",update=FALSE)
install("fdrtool",update=FALSE)
install("fgsea",update=FALSE)
install("flashClust",update=FALSE)
install("gage",update=FALSE)
install("genefilter",update=FALSE)
install("ggplot2",update=FALSE)
install("ggrepel",update=FALSE)
install("limma",update=FALSE)
install("pathview",update=FALSE)
install("plyr",update=FALSE)
install("pvclust",update=FALSE)
install("reactome.db",update=FALSE)
install("rgl",update=FALSE)
install("shiny",update=FALSE)
install("topGO",update=FALSE)
